services:
  biblioteca-db:
    image: postgres:15-alpine
    container_name: biblioteca-db
    ports:
      - '6000:5432'
    environment:
      POSTGRES_USER: rem
      POSTGRES_PASSWORD: rem123
      POSTGRES_DB: bibliotecadb
    volumes:
      - biblioteca_pg_data:/var/lib/postgresql/data
    networks:
      - biblioteca-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: haru@rem.com
      PGADMIN_DEFAULT_PASSWORD: rem123
    ports:
      - '6001:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - biblioteca-db
    networks:
      - biblioteca-network

  minio:
    image: minio/minio:latest
    container_name: biblioteca-minio
    command: server /data --console-address ":9001"
    ports:
      - '6002:9000'
      - '6003:9001'
    environment:
      MINIO_ROOT_USER: adminbiblioteca
      MINIO_ROOT_PASSWORD: biblio123456
    volumes:
      - biblioteca_minio_data:/data
    networks:
      - biblioteca-network

volumes:
  biblioteca_pg_data:
  pgadmin_data:
  biblioteca_minio_data:

networks:
  biblioteca-network:
